POST http://localhost:5000/insert
Content-Type: application/json

{
    "col": "teachers",
    "data": {
        "name": "Daryl Cabagay",
        "designation": "Instructor I",
        "description": "Part-Time"
    }
}
###
POST http://localhost:5000/insert
Content-Type: application/json

{
    "col": "class_schedule",
    "data": {
        "subject": "Science",
        "description": "Just a subject",
        "course": "STEM",
        "teacher": "63f51dfbe895e37270c6c45b",
        "days": ["Mon", "Wed", "Fri"],
        "time": ["10:30 AM", "12:00 PM"]
    }
}
###

POST http://localhost:5000/insert
Content-Type: application/json

{
    "col": "users",
    "data": {
        "username": "admin",
        "password": "$2a$12$foRhnB/Dp3k6KAGSunWcy.Yy8zF4emUarKGrX62c9p1dqKJbaPoCu",
        "isAdmin": true
    }
}
###

POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "user",
    "password": "password"
}
###
POST http://localhost:5000/get
Content-Type: application/json

{
    "col": "students",
    "query": {},
    "select": ""
}